# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wmakaran <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/12 10:18:59 by wmakaran          #+#    #+#              #
#    Updated: 2022/12/12 10:20:49 by wmakaran         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	cc -Wall -Wextra -Werror main.c map_comparisons.c map_io.c map_io_helper_functions.c read_map_names.c square.c -o bsq

clean:

fclean: clean
	rm -f bsq
