# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wmakaran <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/12 13:41:26 by wmakaran          #+#    #+#              #
#    Updated: 2022/12/12 13:43:39 by wmakaran         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	cc -Wall -Wextra -Werror do-op.c ft_atoi.c ft_operators.c ft_putstr.c ft_strcmp.c -o do-op

clean:

fclean:
	rm -f do-op
