# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wmakaran <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/08 11:45:50 by wmakaran          #+#    #+#              #
#    Updated: 2022/12/11 15:20:01 by wmakaran         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	cc -Wall -Wextra -Werror ft_display_file.c -o ft_display_file

clean:

fclean: clean
	rm -f ft_display_file
